# ### sqlite3

#
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#
# development:
#   <<: *default
#   database: db/development.sqlite3
#
# test:
#   <<: *default
#   database: db/test.sqlite3
#
# production:
#   <<: *default
#   database: db/production.sqlite3

# For psql  =======================================================

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: ciap_development
  pool: 5
  # username: root
  # password:


test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: ciap_test
  pool: 5
  # username: root
  # password:

production:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: ciap_production
  pool: 5
  # username: root
  # password:
